#!/bin/sh

# code modified from:
# `man nmcli-examples` and Copyright 2012 Johannes Buchner <buchner.johannes@gmx.at> Copyright 2012 - 2014 Red Hat, Inc.

enable_disable_wifi ()
{
	if nmcli -t --fields type,state device | grep -q 'ethernet:connected'; then
		nmcli radio wifi off
	else
		nmcli radio wifi on
	fi
}

case "$2" in
	up|down) enable_disable_wifi;;
esac
